<div style="float:left; padding-right:16px;"><?php echo $this->gravatar($this->zfcUserIdentity()->getEmail()) ?></div>
<h3><?php echo $this->translate('Hello'); ?>, <?php echo $this->zfcUserDisplayName() ?></h3>
<h3><?php echo $this->translate('Email: '); ?> <?php echo $this->zfcUserEmail() ?></h3>
<h3><?php echo $this->translate('Last Name: '); ?> <?php echo $this->zfcUserLastName() ?></h3>
<h3><?php echo $this->translate('Gender: '); ?> <?php echo $this->zfcUserGender() ?></h3>
<h3><?php echo $this->translate('Birthdate: '); ?> <?php echo $this->zfcUserBirthdate() ?></h3>
<h3><?php echo $this->translate('Phone Number: '); ?> <?php echo $this->zfcUserPhoneNumber() ?></h3>
<h3><?php echo $this->translate('Address: '); ?> <?php echo $this->zfcUserAddress() ?></h3>
<h3><?php echo $this->translate('Country: '); ?> <?php echo $this->zfcUserCountry() ?></h3>
<h3><?php echo $this->translate('Region: '); ?> <?php echo $this->zfcUserRegion() ?></h3>
<h3><?php echo $this->translate('City: '); ?> <?php echo $this->zfcUserCity() ?></h3>
<h3><?php echo $this->translate('Zip: '); ?> <?php echo $this->zfcUserZip() ?></h3>
<a href="<?php echo $this->url('zfcuser/logout') ?>">[<?php echo $this->translate('Sign Out'); ?>]</a>
<div style="clear:both;"></div>
